[package]
name = "scratch-index"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["cargo", "derive"] }
git2 = "0.19.0"
serde_yaml = "0.9.34"
