[package]
name = "gorilla"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.10.1"
criterion = "0.5.1"

[dev-dependencies]
proptest = "1.6.0"

[[bench]]
name = "gorilla_benchmark"
harness = false
