name: GitHub Pages Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Generate index.md
        run: |
          cd scratch-index
          cargo run -- .. --only-language HTML > ../index.md
          rm -rf target

      - name: Convert index.md to html
        uses: docker://pandoc/core:3.5
        with:
          args: >-
            --standalone
            --output=index.html
            index.md

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
